name: Corgis go Ruff
on:
    push:
        paths:
            - "**.py"
jobs:
    format:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Install uv
              run: curl -Ls https://astral.sh/uv/install.sh | bash

            - name: Sync dependencies
              run: uv sync

            - name: Run formatter
              run: make format-all
